export type AbsenceDeleteStatus = string | null | undefined;

export interface AbsenceDeleteGuardInput {
  date: string | null | undefined;
  status: AbsenceDeleteStatus;
  isBankHoliday?: boolean | null;
  autoGenerated?: boolean | null;
  bulkBatchId?: string | null;
  recordSource?: string | null;
  hasEditScope: boolean;
  isFullAccessAdmin: boolean;
  /** Injectable for tests; defaults to local calendar today as YYYY-MM-DD. */
  todayIso?: string;
}

export interface AbsenceDeleteGuardResult {
  allowed: boolean;
  reason: string | null;
}

function normalizeIsoDate(value: string | null | undefined): string | null {
  if (!value) return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  return trimmed.slice(0, 10);
}

export function getTodayIsoDate(now: Date = new Date()): string {
  const year = now.getFullYear();
  const month = String(now.getMonth() + 1).padStart(2, '0');
  const day = String(now.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
}

export function isTakenAbsenceStatus(status: AbsenceDeleteStatus): boolean {
  const normalized = (status || '').trim().toLowerCase();
  return normalized === 'approved' || normalized === 'processed';
}

/**
 * Shared delete policy for absences.
 * DB trigger remains authoritative; this helper is the UX/client safeguard.
 */
export function evaluateAbsenceDeleteGuard(input: AbsenceDeleteGuardInput): AbsenceDeleteGuardResult {
  if (!input.hasEditScope) {
    return { allowed: false, reason: 'You do not have permission to delete this absence.' };
  }

  if (input.recordSource === 'archived') {
    return { allowed: false, reason: 'Archived absences cannot be deleted.' };
  }

  if (input.isBankHoliday) {
    return { allowed: false, reason: 'Bank holidays cannot be deleted individually.' };
  }

  if (input.autoGenerated) {
    return { allowed: false, reason: 'Auto-generated absences cannot be deleted individually.' };
  }

  if (!input.isFullAccessAdmin && input.bulkBatchId) {
    return {
      allowed: false,
      reason: 'Bulk company leave bookings can only be removed by an admin or via Undo Bulk Booking.',
    };
  }

  if (input.isFullAccessAdmin) {
    return { allowed: true, reason: null };
  }

  const absenceDate = normalizeIsoDate(input.date);
  if (!absenceDate) {
    return { allowed: false, reason: 'Absence date is missing.' };
  }

  const todayIso = normalizeIsoDate(input.todayIso) || getTodayIsoDate();
  if (absenceDate < todayIso) {
    return {
      allowed: false,
      reason: 'Past absences can only be deleted by an admin.',
    };
  }

  if (isTakenAbsenceStatus(input.status)) {
    return {
      allowed: false,
      reason: 'Approved or processed absences can only be deleted by an admin.',
    };
  }

  return { allowed: true, reason: null };
}

export function canDeleteAbsenceRecord(input: AbsenceDeleteGuardInput): boolean {
  return evaluateAbsenceDeleteGuard(input).allowed;
}
