import type { FAQCategoryDef } from './types';

export const FAQ_CATEGORIES: FAQCategoryDef[] = [
  {
    slug: 'getting-started',
    name: 'Getting Started',
    description: 'General app access, dashboard, and installation guidance.',
    module_name: null,
    sort_order: 1,
  },
  {
    slug: 'timesheets',
    name: 'Timesheets',
    description: 'Help for creating, editing, and tracking timesheets.',
    module_name: 'timesheets',
    sort_order: 2,
  },
  {
    slug: 'inspections',
    name: 'Van Daily Checks',
    description: 'Help for completing van daily checks and defect reporting.',
    module_name: 'inspections',
    sort_order: 3,
  },
  {
    slug: 'plant-daily-checks',
    name: 'Plant Daily Checks',
    description: 'Help for completing plant machinery daily checks.',
    module_name: 'plant-inspections',
    sort_order: 4,
  },
  {
    slug: 'hgv-daily-checks',
    name: 'HGV Daily Checks',
    description: 'Help for completing HGV daily checks.',
    module_name: 'hgv-inspections',
    sort_order: 5,
  },
  {
    slug: 'projects',
    name: 'Projects',
    description: 'Help for project documents, signatures, and visitor sign-in.',
    module_name: 'rams',
    sort_order: 6,
  },
  {
    slug: 'absence',
    name: 'Absence & Leave',
    description: 'Help for annual leave, calendars, allowances, and absence reporting.',
    module_name: 'absence',
    sort_order: 7,
  },
  {
    slug: 'maintenance',
    name: 'Maintenance',
    description: 'Help for maintenance schedules and service status.',
    module_name: 'maintenance',
    sort_order: 8,
  },
  {
    slug: 'fleet',
    name: 'Fleet',
    description: 'Help for fleet assets, vans, plant, HGVs, and asset history.',
    module_name: 'admin-vans',
    sort_order: 9,
  },
  {
    slug: 'workshop-tasks',
    name: 'Workshop Tasks',
    description: 'Help for repair tasks, defects, comments, and workshop workflow.',
    module_name: 'workshop-tasks',
    sort_order: 10,
  },
  {
    slug: 'inventory',
    name: 'Inventory',
    description: 'Help for small tools, minor plant, hardware stock, locations, and Yard kiosk.',
    module_name: 'inventory',
    sort_order: 11,
  },
  {
    slug: 'approvals',
    name: 'Approvals',
    description: 'Help for reviewing timesheets and absence requests.',
    module_name: 'approvals',
    sort_order: 12,
  },
  {
    slug: 'actions',
    name: 'Manager Actions Hub',
    description: 'Help for the manager action summary pages.',
    module_name: 'actions',
    sort_order: 13,
  },
  {
    slug: 'toolbox-talks',
    name: 'Toolbox Talks & Reminders',
    description: 'Help for sending and tracking safety messages.',
    module_name: 'toolbox-talks',
    sort_order: 14,
  },
  {
    slug: 'training',
    name: 'Training',
    description: 'Help for training records, people, qualifications, and expiry tracking.',
    module_name: 'training',
    sort_order: 15,
  },
  {
    slug: 'reminders',
    name: 'Reminders',
    description: 'Help for personal task reminders assigned in the app.',
    module_name: 'reminders',
    sort_order: 16,
  },
  {
    slug: 'reports',
    name: 'Reports',
    description: 'Help for operational reports and exports.',
    module_name: 'reports',
    sort_order: 17,
  },
  {
    slug: 'suggestions',
    name: 'Suggestions',
    description: 'Help for reviewing and triaging user suggestions.',
    module_name: 'suggestions',
    sort_order: 18,
  },
  {
    slug: 'customers',
    name: 'Customers',
    description: 'Help for managing customer records and history.',
    module_name: 'customers',
    sort_order: 19,
  },
  {
    slug: 'quotes',
    name: 'Quotes',
    description: 'Help for creating, approving, invoicing, and adjusting customer quotes.',
    module_name: 'quotes',
    sort_order: 20,
  },
  {
    slug: 'admin-users',
    name: 'User Management',
    description: 'Help for admin user and role management.',
    module_name: 'admin-users',
    sort_order: 21,
  },
  {
    slug: 'admin-roles',
    name: 'Roles & Permissions',
    description: 'Help for role and permission setup.',
    module_name: 'admin-users',
    sort_order: 22,
  },
  {
    slug: 'admin-settings',
    name: 'Admin Settings',
    description: 'Help for admin-only settings and configuration.',
    module_name: 'admin-settings',
    sort_order: 23,
  },
  {
    slug: 'faq-editor',
    name: 'FAQ Editor',
    description: 'Help for managing FAQ categories, articles, and visibility.',
    module_name: 'faq-editor',
    sort_order: 24,
  },
  {
    slug: 'error-reports',
    name: 'Error Reports',
    description: 'Help for reviewing user-submitted error reports.',
    module_name: 'error-reports',
    sort_order: 25,
  },
  {
    slug: 'notifications',
    name: 'Notifications & Messages',
    description: 'Help for notifications, reminders, and message acknowledgements.',
    module_name: null,
    sort_order: 26,
  },
  {
    slug: 'troubleshooting',
    name: 'Troubleshooting',
    description: 'General support, refresh, login, and access-denied guidance.',
    module_name: null,
    sort_order: 27,
  },
];
