export interface HgvFieldSpec {
  field_key: string;
  label: string;
  field_type: 'marking_code' | 'text' | 'long_text' | 'number' | 'date' | 'yes_no' | 'signature';
  is_required: boolean;
  help_text?: string | null;
}

export interface HgvSectionSpec {
  section_key: string;
  title: string;
  description: string;
  sort_order: number;
  fields: HgvFieldSpec[];
}

export const HGV_6_WEEK_FULL_SECTION_SPECS: HgvSectionSpec[] = [
  {
    section_key: 'vehicle_and_inspection_details',
    title: 'Vehicle and Inspection Details',
    description: 'Header details recorded before the inspection checklist begins.',
    sort_order: 1,
    fields: [
      { field_key: 'company_name', label: 'Company', field_type: 'text', is_required: true },
      { field_key: 'address', label: 'Address', field_type: 'long_text', is_required: false },
      { field_key: 'make', label: 'Make', field_type: 'text', is_required: true },
      { field_key: 'registration_number', label: 'Reg no.', field_type: 'text', is_required: true },
      { field_key: 'model', label: 'Model', field_type: 'text', is_required: false },
      { field_key: 'fleet_number', label: 'Fleet no.', field_type: 'text', is_required: false },
      { field_key: 'o_licence_review', label: 'O licence review', field_type: 'text', is_required: false },
      { field_key: 'body_type', label: 'Body type', field_type: 'text', is_required: false },
      { field_key: 'vehicle_year', label: 'Year', field_type: 'text', is_required: false },
      { field_key: 'odometer_reading', label: 'Odo reading', field_type: 'number', is_required: true },
      { field_key: 'odometer_unit', label: 'Odo reading unit (miles/km)', field_type: 'text', is_required: false },
      { field_key: 'chassis_number', label: 'Chassis no.', field_type: 'text', is_required: false },
      { field_key: 'tachograph_calibration_date', label: 'Tachograph calibration date', field_type: 'date', is_required: false },
      { field_key: 'tachograph_two_year_test_date', label: 'Tachograph last 2 year test date', field_type: 'date', is_required: false },
      { field_key: 'inspection_date', label: 'Inspection date', field_type: 'date', is_required: true },
      { field_key: 'iso_week_number', label: 'ISO week no.', field_type: 'text', is_required: false },
    ],
  },
  {
    section_key: 'inside_cab',
    title: 'Inside Cab',
    description: 'Part 1 checklist items under INSIDE CAB.',
    sort_order: 2,
    fields: [
      { field_key: 'engine_mil', label: 'Engine MIL', field_type: 'marking_code', is_required: true },
      { field_key: 'reagent_adblue', label: 'Reagent (AdBlue)', field_type: 'marking_code', is_required: true },
      { field_key: 'dft_plate_condition', label: 'DfT plate - condition-details', field_type: 'marking_code', is_required: true },
      { field_key: 'speed_limiter_plate_condition', label: 'Speed limiter plate - condition-details', field_type: 'marking_code', is_required: true },
      { field_key: 'seat_belts_restraints', label: 'Seat belts and supplementary restraint systems - condition', field_type: 'marking_code', is_required: true },
      { field_key: 'cab_floor_steps_inside', label: 'Cab floor and steps (inside cab)', field_type: 'marking_code', is_required: true },
      { field_key: 'seats', label: 'Seats', field_type: 'marking_code', is_required: true },
      { field_key: 'other_seats_and_crew_amenities', label: 'Other seats and crew amenities', field_type: 'marking_code', is_required: true },
      { field_key: 'mirrors_internal', label: 'Mirrors (internal)', field_type: 'marking_code', is_required: true },
      { field_key: 'view_to_front', label: 'View to front', field_type: 'marking_code', is_required: true },
      { field_key: 'glass_condition', label: 'Condition of glass (screen/windows)', field_type: 'marking_code', is_required: true },
      { field_key: 'wipers_washers', label: 'Windscreen wipers and washers', field_type: 'marking_code', is_required: true },
      { field_key: 'speedometer_tachograph', label: 'Speedometer/tachograph - operation-seals', field_type: 'marking_code', is_required: true },
      { field_key: 'engine_tachometer', label: 'Engine tachometer', field_type: 'marking_code', is_required: true },
      { field_key: 'horn', label: 'Audible warning - horn', field_type: 'marking_code', is_required: true },
      { field_key: 'driving_controls', label: 'Driving controls', field_type: 'marking_code', is_required: true },
      { field_key: 'steering_control_free_play', label: 'Steering control - free play', field_type: 'marking_code', is_required: true },
      { field_key: 'steering_wheel_security', label: 'Steering wheel - security-condition', field_type: 'marking_code', is_required: true },
      { field_key: 'steering_column', label: 'Steering column', field_type: 'marking_code', is_required: true },
      { field_key: 'anti_theft_locks', label: 'Anti-theft locks', field_type: 'marking_code', is_required: true },
      { field_key: 'pressure_vacuum_warning', label: 'Pressure/vacuum - warning', field_type: 'marking_code', is_required: true },
      { field_key: 'pressure_vacuum_build_up', label: 'Pressure/vacuum - build up', field_type: 'marking_code', is_required: true },
      { field_key: 'other_gauges_warning', label: 'Other gauges - warning device', field_type: 'marking_code', is_required: true },
      { field_key: 'hand_lever_or_electronic_park_brake', label: 'Hand lever, operating mechanical brake systems - electronic park brake control', field_type: 'marking_code', is_required: true },
      { field_key: 'service_brake_pedal', label: 'Service brake pedal', field_type: 'marking_code', is_required: true },
      { field_key: 'service_brake_operation', label: 'Service brake operation/anti-lock warning', field_type: 'marking_code', is_required: true },
      { field_key: 'hand_operated_brake_control_valve', label: 'Hand operated brake control valve', field_type: 'marking_code', is_required: true },
      { field_key: 'electrical_wiring_equipment_switches_cab', label: 'Electrical wiring/equipment/switches', field_type: 'marking_code', is_required: true },
      { field_key: 'front_fog_aux_lamp_switches', label: 'Front fog and aux lamp switches', field_type: 'marking_code', is_required: true },
      { field_key: 'panel_interior_lamps_switches', label: 'Panel/interior lamps and switches', field_type: 'marking_code', is_required: true },
      { field_key: 'cab_heater_demister', label: 'Cab heater/demister/air conditioning', field_type: 'marking_code', is_required: true },
    ],
  },
  {
    section_key: 'cab_exterior_and_engine',
    title: 'Cab Exterior and Engine Compartment',
    description: 'Part 1 checklist items under CAB-EXTERIOR and ENGINE COMPARTMENT.',
    sort_order: 3,
    fields: [
      { field_key: 'front_bumper', label: 'Bumper (front)', field_type: 'marking_code', is_required: true },
      { field_key: 'front_wings_spray_suppression_wheel_arches', label: 'Condition of wings/spray suppression/wheel arches (front)', field_type: 'marking_code', is_required: true },
      { field_key: 'cab_panels_trim_heated_mirrors', label: 'Cab panels, trim and heated mirrors', field_type: 'marking_code', is_required: true },
      { field_key: 'cab_security', label: 'Cab security including tilt warning', field_type: 'marking_code', is_required: true },
      { field_key: 'cab_doors_hinges_locks', label: 'Cab doors including hinges, locks', field_type: 'marking_code', is_required: true },
      { field_key: 'cab_floor_steps_exterior', label: 'Cab floor and steps (cab exterior)', field_type: 'marking_code', is_required: true },
      { field_key: 'external_mirrors', label: 'Mirrors and indirect vision devices (external)', field_type: 'marking_code', is_required: true },
      { field_key: 'front_side_lamps_outline_markers', label: 'Front lamps (side lamps) and outline markers', field_type: 'marking_code', is_required: true },
      { field_key: 'headlamp_cleaning_device', label: 'Headlamp cleaning device', field_type: 'marking_code', is_required: true },
      { field_key: 'day_running_lamps', label: 'Day time running lamps', field_type: 'marking_code', is_required: true },
      { field_key: 'headlamps_operation', label: 'Headlamps - operation-aim-adjustment-mechanisms', field_type: 'marking_code', is_required: true },
      { field_key: 'front_fog_spot_dim_dip_device', label: 'Front fog lamps/spot lamps/dim dip device', field_type: 'marking_code', is_required: true },
      { field_key: 'engine_mountings', label: 'Engine/transmission mountings', field_type: 'marking_code', is_required: true },
      { field_key: 'oil_leaks_engine', label: 'Oil leaks', field_type: 'marking_code', is_required: true },
      { field_key: 'fuel_system_engine', label: 'Fuel tanks and systems', field_type: 'marking_code', is_required: true },
      { field_key: 'exhaust_system_engine', label: 'Exhaust systems', field_type: 'marking_code', is_required: true },
      { field_key: 'exhaust_brake', label: 'Exhaust brake', field_type: 'marking_code', is_required: true },
      { field_key: 'radiator_mounting', label: 'Radiator mounting', field_type: 'marking_code', is_required: true },
      { field_key: 'cooling_system_engine', label: 'Cooling system', field_type: 'marking_code', is_required: true },
      { field_key: 'fan_generator_aux_belts', label: 'Fan, generator, aux belts', field_type: 'marking_code', is_required: true },
      { field_key: 'fuel_pump_linkage_seals_edc', label: 'Fuel pump linkage seals and EDC equipment', field_type: 'marking_code', is_required: true },
      { field_key: 'speed_limiter_seals', label: 'Speed limiter - condition-seals-linkage', field_type: 'marking_code', is_required: true },
      { field_key: 'injectors_pipes_filters', label: 'Injectors, pipes, filters', field_type: 'marking_code', is_required: true },
      { field_key: 'air_intake_turbo_intercooler_filters', label: 'Air intake system - turbocharger intercooler and filters', field_type: 'marking_code', is_required: true },
      { field_key: 'air_compressor_exhauster_drive_belts', label: 'Air compressor - exhauster - drive belts (if applicable)', field_type: 'marking_code', is_required: true },
    ],
  },
  {
    section_key: 'ground_level_and_under_vehicle',
    title: 'Ground Level and Under/Alongside Vehicle',
    description: 'Part 1 checklist items under GROUND LEVEL and UNDER/ALONGSIDE VEHICLE.',
    sort_order: 4,
    fields: [
      { field_key: 'road_wheels_hubs', label: 'Road wheels and hubs', field_type: 'marking_code', is_required: true },
      { field_key: 'sideguards_rear_underrun_bumper_bars', label: 'Sideguards, rear underrun devices and bumper bars', field_type: 'marking_code', is_required: true },
      { field_key: 'spare_wheel_carrier', label: 'Spare wheel carrier (and spare wheel)', field_type: 'marking_code', is_required: true },
      { field_key: 'vehicle_trailer_coupling', label: 'Vehicle to trailer coupling', field_type: 'marking_code', is_required: true },
      { field_key: 'rear_wings_spray_suppression_wheel_arches', label: 'Wings/spray suppression (rear)/wheel arches - condition', field_type: 'marking_code', is_required: true },
      { field_key: 'body_security', label: 'Security/condition of body', field_type: 'marking_code', is_required: true },
      { field_key: 'demountable_bodies_chassis_equipment', label: 'Demountable bodies - chassis mounted equipment', field_type: 'marking_code', is_required: true },
      { field_key: 'body_container_crane_leg_security', label: 'Security of body, containers and crane support legs', field_type: 'marking_code', is_required: true },
      { field_key: 'tipping_gear_hydraulic_rams_pivots_safety_devices', label: 'Tipping gear - hydraulic rams, pivots and safety devices', field_type: 'marking_code', is_required: true },
      { field_key: 'tailboard_hoists', label: 'Tailboard hoists', field_type: 'marking_code', is_required: true },
      { field_key: 'cranes_gantries', label: 'Cranes, gantries', field_type: 'marking_code', is_required: true },
      { field_key: 'other_ancillary_equipment', label: 'Other ancillary equipment', field_type: 'marking_code', is_required: true },
      { field_key: 'chassis_condition', label: 'Chassis - condition', field_type: 'marking_code', is_required: true },
      { field_key: 'electrical_wiring_equipment_batteries', label: 'Electrical wiring and equipment including batteries', field_type: 'marking_code', is_required: true },
      { field_key: 'electrical_connections_for_trailer', label: 'Electrical connections for trailer', field_type: 'marking_code', is_required: true },
      { field_key: 'oil_leaks_under_vehicle', label: 'Oil leaks', field_type: 'marking_code', is_required: true },
      { field_key: 'fuel_tanks_systems_under_vehicle', label: 'Fuel tanks and systems', field_type: 'marking_code', is_required: true },
      { field_key: 'exhaust_system_under_vehicle', label: 'Exhaust system', field_type: 'marking_code', is_required: true },
      { field_key: 'suspension_pins_bushes_condition', label: 'Suspension pins and bushes - condition', field_type: 'marking_code', is_required: true },
      { field_key: 'suspension_units_linkages_condition', label: 'Suspension units and linkages - condition', field_type: 'marking_code', is_required: true },
      { field_key: 'spring_units_linkages_subframes_security', label: 'Spring units, linkages and sub-frames - security', field_type: 'marking_code', is_required: true },
      { field_key: 'shock_absorbers', label: 'Shock absorbers', field_type: 'marking_code', is_required: true },
      { field_key: 'rear_wheel_bearings_seals', label: 'Wheel bearings and seals (rear)', field_type: 'marking_code', is_required: true },
      { field_key: 'axles_stub_axles_wheel_bearings', label: 'Axles/stub axles and wheel bearings', field_type: 'marking_code', is_required: true },
      { field_key: 'steering_mechanism', label: 'Steering mechanism', field_type: 'marking_code', is_required: true },
      { field_key: 'steering_alignment', label: 'Steering alignment', field_type: 'marking_code', is_required: true },
      { field_key: 'power_steering', label: 'Power steering and fluid level', field_type: 'marking_code', is_required: true },
      { field_key: 'axle_alignment', label: 'Axle alignment', field_type: 'marking_code', is_required: true },
      { field_key: 'clutch_operation', label: 'Clutch operation', field_type: 'marking_code', is_required: true },
      { field_key: 'gearbox_bell_housing', label: 'Gearbox and bell housing', field_type: 'marking_code', is_required: true },
      { field_key: 'change_speed_mechanism', label: 'Change speed mechanism', field_type: 'marking_code', is_required: true },
      { field_key: 'power_take_off', label: 'Power take-off', field_type: 'marking_code', is_required: true },
      { field_key: 'final_drive', label: 'Final drive', field_type: 'marking_code', is_required: true },
      { field_key: 'two_speed_shift_mechanism', label: '2-speed shift mechanism', field_type: 'marking_code', is_required: true },
      { field_key: 'differential_lock_traction_control', label: 'Differential lock - traction control', field_type: 'marking_code', is_required: true },
      { field_key: 'load_transfer_axle_lift_device', label: 'Load transfer/axle lift device', field_type: 'marking_code', is_required: true },
      { field_key: 'transmission_mountings', label: 'Transmission - drive line-mountings', field_type: 'marking_code', is_required: true },
      { field_key: 'electronic_braking_stability_system_operation_warning', label: 'Electronic braking system/electronic stability control system - operation-warning', field_type: 'marking_code', is_required: true },
      { field_key: 'hydraulic_fluid_level', label: 'Hydraulic fluid level', field_type: 'marking_code', is_required: true, help_text: 'IM no: 48' },
      { field_key: 'mechanical_brake_components', label: 'Mechanical brake components', field_type: 'marking_code', is_required: true, help_text: 'IM no: 59' },
      { field_key: 'drums_discs_pads', label: 'Drums and linings/discs and pads', field_type: 'marking_code', is_required: true, help_text: 'IM no: 59' },
      { field_key: 'brake_actuators_adjusters', label: 'Brake actuators and adjusters', field_type: 'marking_code', is_required: true, help_text: 'IM no: 59' },
      { field_key: 'brake_system_components', label: 'Brake systems and components', field_type: 'marking_code', is_required: true, help_text: 'IM no: 59' },
      { field_key: 'trailer_couplings_hoses_self_sealing_valves', label: 'Trailer couplings, hoses and function of self-sealing valves', field_type: 'marking_code', is_required: true },
      { field_key: 'load_sensing_anti_lock_system', label: 'Load sensing/anti-lock system', field_type: 'marking_code', is_required: true },
      { field_key: 'air_brake_anti_freeze_device', label: 'Air brake anti-freeze device', field_type: 'marking_code', is_required: true },
      { field_key: 'anti_lock_device_operation_warning', label: 'Anti-lock device - operation/warning', field_type: 'marking_code', is_required: true, help_text: 'IM no: 38' },
      { field_key: 'supply_dump_valve_operation', label: 'Operation of supply dump valve', field_type: 'marking_code', is_required: true },
      { field_key: 'multi_circuit_protection_operation', label: 'Operation of multi-circuit protection', field_type: 'marking_code', is_required: true },
      { field_key: 'additional_braking_devices', label: 'Additional braking devices', field_type: 'marking_code', is_required: true },
      { field_key: 'rear_markings_conspicuity_markings', label: 'Rear markings and conspicuity markings', field_type: 'marking_code', is_required: true },
      { field_key: 'rear_lamps_outline_markers_number_plate_lamp', label: 'Rear lamps, outline markers and number plate lamp', field_type: 'marking_code', is_required: true },
      { field_key: 'rear_fog_lamps_warning_device', label: 'Rear fog lamps including warning device', field_type: 'marking_code', is_required: true },
      { field_key: 'reflectors_side_rear', label: 'Reflectors (side and rear)', field_type: 'marking_code', is_required: true },
      { field_key: 'direction_hazard_indicators_warning', label: 'Direction/hazard indicators including warning device', field_type: 'marking_code', is_required: true },
      { field_key: 'side_marker_lamps', label: 'Side marker lamps', field_type: 'marking_code', is_required: true },
      { field_key: 'stop_lamps', label: 'Stop lamps', field_type: 'marking_code', is_required: true },
      { field_key: 'reversing_lamps', label: 'Reversing lamps', field_type: 'marking_code', is_required: true },
      { field_key: 'position_lamps_headlamps_warning_device', label: 'Position lamps, headlamps and warning device', field_type: 'marking_code', is_required: true },
      { field_key: 'other_lamps', label: 'Other lamps', field_type: 'marking_code', is_required: true },
      { field_key: 'paintwork_livery_condition', label: 'Paintwork and livery - condition', field_type: 'marking_code', is_required: true },
      { field_key: 'licences', label: 'Licences', field_type: 'marking_code', is_required: true },
      { field_key: 'legal_writing', label: 'Legal writing', field_type: 'marking_code', is_required: true },
      { field_key: 'registration_plates', label: 'Registration plates', field_type: 'marking_code', is_required: true },
      { field_key: 'other_dangerous_defects', label: 'Other dangerous defects', field_type: 'marking_code', is_required: true },
    ],
  },
  {
    section_key: 'tyres_and_brakes',
    title: 'Tyres, Emissions, and Measurements',
    description: 'Part 1 emissions and tyres table fields including explicit measurement cells.',
    sort_order: 5,
    fields: [
      { field_key: 'exhaust_emission_result', label: 'Exhaust emission', field_type: 'text', is_required: false, help_text: 'IM no: 38' },
      { field_key: 'tyre_size_type', label: 'Size and type of tyres', field_type: 'text', is_required: true, help_text: 'IM no: 54' },
      { field_key: 'tyre_condition', label: 'Condition of tyres', field_type: 'long_text', is_required: true, help_text: 'IM no: 54' },
      { field_key: 'tread_wear_pressure', label: 'TREAD WEAR/PRESSURE (strike out/amend boxes)', field_type: 'long_text', is_required: true, help_text: 'IM no: 57' },
      { field_key: 'tyre_01_tread_mm', label: 'Tyre position 1 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_01_pressure_psi', label: 'Tyre position 1 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_02_tread_mm', label: 'Tyre position 2 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_02_pressure_psi', label: 'Tyre position 2 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_03_tread_mm', label: 'Tyre position 3 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_03_pressure_psi', label: 'Tyre position 3 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_04_tread_mm', label: 'Tyre position 4 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_04_pressure_psi', label: 'Tyre position 4 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_05_tread_mm', label: 'Tyre position 5 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_05_pressure_psi', label: 'Tyre position 5 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_06_tread_mm', label: 'Tyre position 6 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_06_pressure_psi', label: 'Tyre position 6 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_07_tread_mm', label: 'Tyre position 7 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_07_pressure_psi', label: 'Tyre position 7 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_08_tread_mm', label: 'Tyre position 8 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_08_pressure_psi', label: 'Tyre position 8 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_09_tread_mm', label: 'Tyre position 9 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_09_pressure_psi', label: 'Tyre position 9 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_10_tread_mm', label: 'Tyre position 10 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_10_pressure_psi', label: 'Tyre position 10 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_11_tread_mm', label: 'Tyre position 11 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_11_pressure_psi', label: 'Tyre position 11 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_12_tread_mm', label: 'Tyre position 12 tread (mm)', field_type: 'number', is_required: false },
      { field_key: 'tyre_12_pressure_psi', label: 'Tyre position 12 pressure (psi)', field_type: 'number', is_required: false },
      { field_key: 'tyre_age_marking_01', label: 'Tyre age marking position 1', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_marking_02', label: 'Tyre age marking position 2', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_marking_03', label: 'Tyre age marking position 3', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_marking_04', label: 'Tyre age marking position 4', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_marking_05', label: 'Tyre age marking position 5', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_marking_06', label: 'Tyre age marking position 6', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_marking_07', label: 'Tyre age marking position 7', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_marking_08', label: 'Tyre age marking position 8', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_marking_09', label: 'Tyre age marking position 9', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_marking_10', label: 'Tyre age marking position 10', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_marking_11', label: 'Tyre age marking position 11', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_marking_12', label: 'Tyre age marking position 12', field_type: 'text', is_required: false },
      { field_key: 'tyre_age_markings_notes', label: 'TYRE AGE MARKINGS notes (NV if not visible)', field_type: 'long_text', is_required: false, help_text: 'IM no: 74' },
    ],
  },
  {
    section_key: 'rectification_actions',
    title: 'Part 2: Rectification',
    description: 'Fault details, actions taken, and rectification sign-off fields from page 3.',
    sort_order: 6,
    fields: [
      { field_key: 'faults_immediate_attention', label: 'Needing immediate attention', field_type: 'long_text', is_required: false },
      { field_key: 'faults_early_attention', label: 'Less urgent - for early attention', field_type: 'long_text', is_required: false },
      { field_key: 'rectification_im_number', label: 'IM No', field_type: 'text', is_required: false },
      { field_key: 'rectification_fault_number', label: 'Fault no', field_type: 'text', is_required: false },
      { field_key: 'actions_taken', label: 'ACTION TAKEN TO RECTIFY FAULTS', field_type: 'long_text', is_required: false },
      { field_key: 'rectified_by', label: 'RECTIFIED BY', field_type: 'text', is_required: false },
      { field_key: 'driver_defect_report_items', label: 'Faults numbered here are Driver Defect Report items', field_type: 'long_text', is_required: false },
      { field_key: 'vehicle_safe_roadworthy_declaration', label: 'Vehicle now in a safe and roadworthy condition', field_type: 'yes_no', is_required: false },
      { field_key: 'rectification_declaration_notes', label: 'Rectification declaration comments', field_type: 'long_text', is_required: false },
      { field_key: 'rectification_completed_date', label: 'Date completed', field_type: 'date', is_required: false },
      { field_key: 'signature_of_inspector', label: 'Signature of Inspector', field_type: 'signature', is_required: true },
      { field_key: 'inspector_name_rectification', label: 'Name of inspector', field_type: 'text', is_required: true },
      { field_key: 'inspector_position_rectification', label: 'Position', field_type: 'text', is_required: false },
    ],
  },
  {
    section_key: 'road_brake_test_and_declaration',
    title: 'Part 3: Road/Brake Test Report',
    description: 'Road speed limiter, brake test values, load condition, and tester sign-off.',
    sort_order: 7,
    fields: [
      { field_key: 'road_speed_limiter_operational', label: 'ROAD SPEED LIMITER operational YES/NO*', field_type: 'yes_no', is_required: true },
      { field_key: 'set_speed_kph', label: 'Set speed (kph)', field_type: 'number', is_required: false },
      { field_key: 'set_speed_mph', label: 'Set speed (mph)', field_type: 'number', is_required: false },
      { field_key: 'road_conditions', label: 'Road conditions', field_type: 'text', is_required: false },
      { field_key: 'service_brake_result', label: 'Service [IM no 71] (%)', field_type: 'number', is_required: false, help_text: 'IM no: 71' },
      { field_key: 'secondary_brake_result', label: 'Secondary [IM no 72] (%)', field_type: 'number', is_required: false, help_text: 'IM no: 72' },
      { field_key: 'parking_brake_result', label: 'Parking [IM no 73] (%)', field_type: 'number', is_required: false, help_text: 'IM no: 73' },
      { field_key: 'service_brake_kph', label: 'Service [IM no 71] (kph)', field_type: 'number', is_required: false, help_text: 'IM no: 71' },
      { field_key: 'service_brake_mph', label: 'Service [IM no 71] (mph)', field_type: 'number', is_required: false, help_text: 'IM no: 71' },
      { field_key: 'secondary_brake_kph', label: 'Secondary [IM no 72] (kph)', field_type: 'number', is_required: false, help_text: 'IM no: 72' },
      { field_key: 'secondary_brake_mph', label: 'Secondary [IM no 72] (mph)', field_type: 'number', is_required: false, help_text: 'IM no: 72' },
      { field_key: 'parking_brake_kph', label: 'Parking [IM no 73] (kph)', field_type: 'number', is_required: false, help_text: 'IM no: 73' },
      { field_key: 'parking_brake_mph', label: 'Parking [IM no 73] (mph)', field_type: 'number', is_required: false, help_text: 'IM no: 73' },
      { field_key: 'celerometer_test_result', label: 'celerometer test*', field_type: 'text', is_required: false },
      { field_key: 'roller_brake_test_result', label: 'Roller brake test*', field_type: 'text', is_required: false },
      { field_key: 'road_test_overall_comments', label: 'ROAD TEST - OVERALL COMMENTS', field_type: 'long_text', is_required: false },
      { field_key: 'load_condition', label: 'Load condition of vehicle (Laden*/Unladen*)', field_type: 'text', is_required: true },
      { field_key: 'road_test_comments', label: 'Comments', field_type: 'long_text', is_required: false },
      { field_key: 'tester_signature', label: 'Signature of Road/Brake tester', field_type: 'signature', is_required: true },
      { field_key: 'tester_name', label: 'Tester name', field_type: 'text', is_required: false },
      { field_key: 'tester_position', label: 'Tester position', field_type: 'text', is_required: false },
      { field_key: 'brake_temperature_pc_axle_1_c', label: 'BRAKE TEMPERATURE ASSESSMENT PC Axle 1 (C)', field_type: 'number', is_required: false },
      { field_key: 'brake_temperature_pc_axle_2_c', label: 'BRAKE TEMPERATURE ASSESSMENT PC Axle 2 (C)', field_type: 'number', is_required: false },
      { field_key: 'brake_temperature_pc_axle_3_c', label: 'BRAKE TEMPERATURE ASSESSMENT PC Axle 3 (C)', field_type: 'number', is_required: false },
      { field_key: 'brake_temperature_pc_axle_4_c', label: 'BRAKE TEMPERATURE ASSESSMENT PC Axle 4 (C)', field_type: 'number', is_required: false },
      { field_key: 'brake_temperature_ns_axle_1_c', label: 'BRAKE TEMPERATURE ASSESSMENT N/S Axle 1 (C)', field_type: 'number', is_required: false },
      { field_key: 'brake_temperature_ns_axle_2_c', label: 'BRAKE TEMPERATURE ASSESSMENT N/S Axle 2 (C)', field_type: 'number', is_required: false },
      { field_key: 'brake_temperature_ns_axle_3_c', label: 'BRAKE TEMPERATURE ASSESSMENT N/S Axle 3 (C)', field_type: 'number', is_required: false },
      { field_key: 'brake_temperature_ns_axle_4_c', label: 'BRAKE TEMPERATURE ASSESSMENT N/S Axle 4 (C)', field_type: 'number', is_required: false },
      { field_key: 'date_of_braking_assessment', label: 'Date of braking assessment', field_type: 'date', is_required: false },
      { field_key: 'digital_tachograph_download', label: 'OPTIONAL Digital tachograph data download YES/NO*', field_type: 'yes_no', is_required: false },
    ],
  },
];

export function countHgv6WeekFullFields(): number {
  return HGV_6_WEEK_FULL_SECTION_SPECS.reduce((total, section) => total + section.fields.length, 0);
}
