import { describe, expect, it } from 'vitest';
import {
  canDeleteAbsenceRecord,
  evaluateAbsenceDeleteGuard,
} from '@/lib/utils/absence-delete-guard';

const today = '2026-08-04';

describe('absence delete guard', () => {
  it('ABS-DEL-01: rejects past pending deletion for non-full admins', () => {
    const result = evaluateAbsenceDeleteGuard({
      date: '2026-08-03',
      status: 'pending',
      hasEditScope: true,
      isFullAccessAdmin: false,
      todayIso: today,
    });

    expect(result.allowed).toBe(false);
    expect(result.reason).toMatch(/past absences/i);
    expect(
      canDeleteAbsenceRecord({
        date: '2026-08-03',
        status: 'pending',
        hasEditScope: true,
        isFullAccessAdmin: false,
        todayIso: today,
      })
    ).toBe(false);
  });

  it('ABS-DEL-02: rejects approved or processed deletion for non-full admins, including future dates', () => {
    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-08-10',
        status: 'approved',
        hasEditScope: true,
        isFullAccessAdmin: false,
        todayIso: today,
      }).allowed
    ).toBe(false);

    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-08-10',
        status: 'processed',
        hasEditScope: true,
        isFullAccessAdmin: false,
        todayIso: today,
      }).allowed
    ).toBe(false);
  });

  it('ABS-DEL-03: allows scoped future pending deletion and denies protected records', () => {
    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-08-04',
        status: 'pending',
        hasEditScope: true,
        isFullAccessAdmin: false,
        todayIso: today,
      }).allowed
    ).toBe(true);

    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-08-10',
        status: 'pending',
        hasEditScope: true,
        isFullAccessAdmin: false,
        todayIso: today,
      }).allowed
    ).toBe(true);

    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-08-10',
        status: 'pending',
        hasEditScope: false,
        isFullAccessAdmin: false,
        todayIso: today,
      }).allowed
    ).toBe(false);

    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-08-10',
        status: 'pending',
        isBankHoliday: true,
        hasEditScope: true,
        isFullAccessAdmin: false,
        todayIso: today,
      }).allowed
    ).toBe(false);

    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-08-10',
        status: 'pending',
        autoGenerated: true,
        hasEditScope: true,
        isFullAccessAdmin: false,
        todayIso: today,
      }).allowed
    ).toBe(false);

    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-08-10',
        status: 'pending',
        bulkBatchId: 'batch-1',
        hasEditScope: true,
        isFullAccessAdmin: false,
        todayIso: today,
      }).allowed
    ).toBe(false);
  });

  it('ABS-DEL-04: effective admin bypasses date/status but not protected-record rules', () => {
    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-01-01',
        status: 'processed',
        hasEditScope: true,
        isFullAccessAdmin: true,
        todayIso: today,
      }).allowed
    ).toBe(true);

    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-01-01',
        status: 'processed',
        isBankHoliday: true,
        hasEditScope: true,
        isFullAccessAdmin: true,
        todayIso: today,
      }).allowed
    ).toBe(false);

    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-01-01',
        status: 'processed',
        autoGenerated: true,
        hasEditScope: true,
        isFullAccessAdmin: true,
        todayIso: today,
      }).allowed
    ).toBe(false);

    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-01-01',
        status: 'processed',
        recordSource: 'archived',
        hasEditScope: true,
        isFullAccessAdmin: true,
        todayIso: today,
      }).allowed
    ).toBe(false);
  });

  it('ABS-DEL-04 view-as: non-full-access effective role keeps historic lock', () => {
    // useDeleteAbsence / manage UI pass isFullAccessAdmin from view-as-aware auth flags.
    expect(
      evaluateAbsenceDeleteGuard({
        date: '2026-01-01',
        status: 'processed',
        hasEditScope: true,
        isFullAccessAdmin: false,
        todayIso: today,
      }).allowed
    ).toBe(false);
  });
});

