import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import {
  FAQ_CATALOGUE_ARTICLES,
  FAQ_CATALOGUE_CATEGORIES,
  assertCatalogueIntegrity,
} from './faq-catalogue';

const MODULE_NAMES = [
  'timesheets',
  'inspections',
  'plant-inspections',
  'hgv-inspections',
  'rams',
  'absence',
  'maintenance',
  'toolbox-talks',
  'training',
  'workshop-tasks',
  'approvals',
  'actions',
  'reports',
  'suggestions',
  'faq-editor',
  'error-reports',
  'admin-users',
  'admin-settings',
  'admin-vans',
  'customers',
  'quotes',
  'inventory',
  'reminders',
] as const;

const SQL_PATH = resolve(process.cwd(), 'supabase/migrations/20260717_help_faq_full_catalogue.sql');
const SEED_PATH = resolve(process.cwd(), 'scripts/seed/data/faq-howto.json');

function sqlString(value: string | null): string {
  if (value === null) return 'NULL';
  return `'${value.replace(/'/g, "''")}'`;
}

function buildSql(): string {
  const moduleList = MODULE_NAMES.map((name) => `          '${name}'`).join(',\n');

  const categoryValues = FAQ_CATALOGUE_CATEGORIES.map((category) => {
    return `  (${sqlString(category.name)}, ${sqlString(category.slug)}, ${sqlString(category.description)}, ${sqlString(category.module_name)}, ${category.sort_order}, TRUE)`;
  }).join(',\n');

  const articleSql = FAQ_CATALOGUE_ARTICLES.map((article) => {
    return `SELECT pg_temp.upsert_faq_article(
  ${sqlString(article.category_slug)},
  ${sqlString(article.title)},
  ${sqlString(article.slug)},
  ${sqlString(article.summary)},
  $md$${article.content_md}$md$,
  ${article.sort_order}
);`;
  }).join('\n\n');

  return `-- Full Help FAQ catalogue refresh for current app modules and features.
-- Generated by scripts/help/generate-faq-full-catalogue.ts — edit catalogue sources, then regenerate.

ALTER TABLE public.faq_categories
  ADD COLUMN IF NOT EXISTS module_name TEXT;

ALTER TABLE public.faq_categories
  DROP CONSTRAINT IF EXISTS faq_categories_module_name_check;

ALTER TABLE public.faq_categories
  ADD CONSTRAINT faq_categories_module_name_check
  CHECK (
    module_name IS NULL OR module_name IN (
${moduleList}
    )
  );

CREATE INDEX IF NOT EXISTS idx_faq_categories_module_name
  ON public.faq_categories(module_name);

UPDATE public.faq_categories
SET
  name = 'Van Daily Checks',
  description = 'Help for completing van daily checks and defect reporting.',
  module_name = 'inspections',
  sort_order = 3
WHERE slug = 'inspections';

UPDATE public.faq_categories
SET
  name = 'Projects',
  slug = 'projects',
  description = 'Help for project documents, signatures, and visitor sign-in.',
  module_name = 'rams',
  sort_order = 6
WHERE slug IN ('rams', 'projects');

UPDATE public.faq_categories
SET
  name = 'Maintenance',
  slug = 'maintenance',
  description = 'Help for maintenance schedules and service status.',
  module_name = 'maintenance',
  sort_order = 8
WHERE slug IN ('fleet-maintenance', 'maintenance');

INSERT INTO public.faq_categories (name, slug, description, module_name, sort_order, is_active)
VALUES
${categoryValues}
ON CONFLICT (slug) DO UPDATE
SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  module_name = EXCLUDED.module_name,
  sort_order = EXCLUDED.sort_order,
  is_active = EXCLUDED.is_active;

UPDATE public.faq_articles
SET category_id = (SELECT id FROM public.faq_categories WHERE slug = 'fleet')
WHERE slug IN ('manage-vehicles', 'fleet-overview', 'vehicle-categories')
  AND category_id = (SELECT id FROM public.faq_categories WHERE slug = 'maintenance');

CREATE OR REPLACE FUNCTION pg_temp.upsert_faq_article(
  p_category_slug TEXT,
  p_title TEXT,
  p_slug TEXT,
  p_summary TEXT,
  p_content_md TEXT,
  p_sort_order INTEGER
)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
  v_category_id UUID;
BEGIN
  SELECT id INTO v_category_id
  FROM public.faq_categories
  WHERE slug = p_category_slug;

  IF v_category_id IS NULL THEN
    RAISE EXCEPTION 'FAQ category not found: %', p_category_slug;
  END IF;

  INSERT INTO public.faq_articles (
    category_id,
    title,
    slug,
    summary,
    content_md,
    is_published,
    sort_order
  )
  VALUES (
    v_category_id,
    p_title,
    p_slug,
    p_summary,
    p_content_md,
    TRUE,
    p_sort_order
  )
  ON CONFLICT (category_id, slug) DO UPDATE
  SET
    title = EXCLUDED.title,
    summary = EXCLUDED.summary,
    content_md = EXCLUDED.content_md,
    is_published = TRUE,
    sort_order = EXCLUDED.sort_order;
END;
$$;

${articleSql}
`;
}

function buildSeedJson(): string {
  const payload = {
    categories: FAQ_CATALOGUE_CATEGORIES.map((category) => ({
      slug: category.slug,
      name: category.name,
      description: category.description,
      module_name: category.module_name,
      sort_order: category.sort_order,
    })),
    articles: FAQ_CATALOGUE_ARTICLES.map((article) => ({
      category_slug: article.category_slug,
      slug: article.slug,
      title: article.title,
      summary: article.summary,
      content_md: article.content_md,
      sort_order: article.sort_order,
    })),
  };

  return `${JSON.stringify(payload, null, 2)}\n`;
}

function main(): void {
  assertCatalogueIntegrity();

  for (const article of FAQ_CATALOGUE_ARTICLES) {
    if (article.content_md.includes('$md$')) {
      throw new Error(`Article ${article.slug} contains forbidden $md$ delimiter`);
    }
  }

  mkdirSync(dirname(SQL_PATH), { recursive: true });
  writeFileSync(SQL_PATH, buildSql(), 'utf8');
  writeFileSync(SEED_PATH, buildSeedJson(), 'utf8');

  console.log(
    `Generated FAQ catalogue: ${FAQ_CATALOGUE_CATEGORIES.length} categories, ${FAQ_CATALOGUE_ARTICLES.length} articles`
  );
  console.log(`SQL: ${SQL_PATH}`);
  console.log(`Seed: ${SEED_PATH}`);
}

main();
